#!/bin/sh -e

script=/usr/bin/rdf-dataset-integration
if [ -x $script ]; then
    package="%%package%%"
    datadir="/usr/share/$package"
    modeluri="%%uri%%"
    $script $@ $datadir $modeluri
else
    echo "Can not process rdf-package automatically (install rdf-dataset-integration for integration)"
fi

#DEBHELPER#
